upstream/test/test.sh
=> Overwrite handling

upstream/test/osr_run.sh, upstream/test/osr_test.sh, upstream/test/test.sh
=> Added ansible.cfg to exec

upstream/test/test.sh
=> Improved debug

.github/workflows/otp_upstream_test_01.yml, Dockerfile, docs/upstream/README.md, upstream/local.yml, upstream/roles/extract_tool_info/defaults/main.yml, upstream/roles/extract_tool_info/tasks/main.yml, upstream/roles/install_kubectl/tasks/main.yml
=> Printing operator tools info

upstream/local.yml, upstream/roles/build_app_registry/defaults/main.yml, upstream/roles/build_app_registry/tasks/main.yml, upstream/roles/build_operator_index/defaults/main.yml, upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/build_operator_version_bundle/defaults/main.yml, upstream/roles/build_operator_version_bundle/tasks/main.yml, upstream/roles/convert_bundle_image_to_dir/defaults/main.yml, upstream/roles/convert_bundle_image_to_dir/tasks/main.yml, upstream/roles/mirror_image/defaults/main.yml, upstream/roles/mirror_image/tasks/mirror_single.yml, upstream/roles/push_to_quay/defaults/main.yml, upstream/roles/push_to_quay/tasks/main.yml, upstream/roles/remove_operator_bundle/defaults/main.yml, upstream/roles/remove_operator_bundle/tasks/main.yml
=> Podman improvments

.github/workflows/playbook_image.yml
=> Added checkout to workflow

roles/install_operator_prereqs/tasks/main.yml, upstream/local.yml, upstream/roles/install_kind/tasks/main.yml, upstream/roles/reset_kind/tasks/reset.yml
=> Bump sdk and fix path for higher versions

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> Improve debug

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> Ordered output

upstream/local.yml
=> olm 0.16.1

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> More general status for running containers

roles/install_operator_prereqs/tasks/main.yml, upstream/local.yml, upstream/roles/install_kind/tasks/main.yml, upstream/roles/reset_kind/tasks/reset.yml
=> Rollback sdk

upstream/local.yml
=> podman as default tool

upstream/test/test.sh
=> Fix channell for kiwi test

upstream/roles/validate_operator_bundle/tasks/main.yml
=> Fixing operator sdk and bundle validate

upstream/local.yml, upstream/roles/install_kind/tasks/main.yml
=> Version bump operator sdk

upstream/roles/install_kind/tasks/main.yml, upstream/roles/reset_kind/tasks/reset.yml
=> Fix operatorsdk fix

upstream/roles/validate_operator_bundle/defaults/main.yml, upstream/roles/validate_operator_bundle/tasks/main.yml
=> Custom categories

upstream/test/test.sh
=> Set strict mode in case of tests

roles/operator_courier_verify/tasks/main.yml, upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/operator_courier_verify/tasks/main.yml, upstream/roles/test_opertator_manifest/tasks/main.yml
Disable operator-courier verify, just push and nest left
=> Disable operator-courier verify

upstream/test/osr_test.sh
=> Strict mode in osr

upstream/test/test.sh
=> Removed iib install in container

upstream/roles/install_iib/templates/docker-compose.yml.j2
=> Fixing format problem to quay

upstream/roles/install_iib/templates/docker-compose.yml.j2
=> Format fix

upstream/roles/mirror_image/tasks/mirror_single.yml
=> Manually removing cache

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
append stderr to all logs
fix installplan debug
=> append stderr to all logs

.github/workflows/otp_upstream_test.yml, upstream/roles/install_operator_prereqs/tasks/main.yml
=> Added iib test

upstream/test/osr_test.sh
=> Fix channel in temp index - default

upstream/test/osr_test.sh
=> Fail temp index when needed

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> Improving debug on namespace

upstream/test/test.sh
=> Added custom script functionality

upstream/roles/build_operator_index/tasks/main.yml
=> Improvemnts in strict mode

upstream/roles/build_operator_index/tasks/main.yml
=> Improve situation when removeing operator

docs/upstream/README.md, upstream/local.yml, upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/check_index/tasks/main.yml, upstream/roles/export_list_of_packages_from_index/defaults/main.yml, upstream/roles/export_list_of_packages_from_index/tasks/main.yml, upstream/roles/mirror_image/tasks/mirror_single.yml, upstream/roles/remove_operator_bundle/tasks/main.yml
Safety check to avoid overwriting full index with empty one
=> Rho 861 avoid index overwrite

upstream/test/test.sh
=> Avoid accidental index destroy

docs/upstream/README.md, upstream/roles/push_to_quay/tasks/delete_from_quay_appreg.yml, upstream/roles/push_to_quay/tasks/main.yml, upstream/roles/push_to_quay/tasks/push_to_quay_appreg.yml
=> delete from appreg

upstream/roles/build_operator_index/tasks/main.yml, upstream/test/osr_test.sh
=> Fix image protocol

upstream/test/test.sh
related to: 
https://github.com/operator-framework/operator-test-playbooks/pull/66
https://github.com/operator-framework/community-operators/pull/3117
=> Activate appreg deletion

upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/install_operator_prereqs/tasks/main.yml, upstream/roles/operator_courier_verify/tasks/main.yml, upstream/roles/operator_push_image/tasks/main.yml
=> Improved check of versions after index add

upstream/roles/operator_courier_verify/tasks/main.yml
=> Courier under strict mode

.github/workflows/otp_upstream_test.yml, .github/workflows/playbook_image.yml
=> Added variab;

roles/build_image_bundle/tasks/main.yml, roles/build_index_bundle/tasks/main.yml, roles/convert_bundle_image_to_dir/tasks/main.yml, roles/extract_operator_bundle/tasks/main.yml, upstream/local-deploy-operator-bundle.yml, upstream/local-test-operator-bundle.yml, upstream/local-test-operator.yml, upstream/local.yml, upstream/roles/build_app_registry/tasks/main.yml, upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/convert_bundle_image_to_dir/tasks/main.yml, upstream/roles/extract_operator_bundle/tasks/main.yml, upstream/roles/mirror_image/tasks/mirror_single.yml, upstream/roles/operator_push_image/tasks/main.yml, upstream/roles/operator_scorecard_tests_bundle/tasks/main.yml, upstream/roles/parse_operator_bundle/tasks/main.yml, upstream/roles/test_opertator_bundle/tasks/main.yml, upstream/roles/test_opertator_manifest/tasks/main.yml, upstream/roles/validate_operator_bundle/tasks/main.yml
=> Remove x509ignoreCN=0

upstream/test/test.sh
=> Added GODEBUG to container

upstream/test/test.sh
=> Improvments in mounting community operators

upstream/roles/reset_kind/templates/kind-with-registry.sh.j2, upstream/test/test.sh
=> Cert dir movments

upstream/roles/validate_operator_bundle/tasks/main.yml
=> External image check to all streams

docs/upstream/README.md, upstream/roles/validate_operator_bundle/tasks/main.yml
Stop empty categories
fix error message for containerImage
fix csv not edited - not looking for containerImage
=> Stop empty categories

upstream/roles/validate_operator_bundle/tasks/main.yml
=> load categories by yq

upstream/roles/validate_operator_bundle/tasks/main.yml
=> Externall image by yq

upstream/roles/build_operator_index/tasks/main.yml
=> Added symmetric_difference

upstream/roles/deploy_olm_operator_upstream_bundle/tasks/main.yml, upstream/roles/deploy_olm_operator_upstream_bundle/tasks/stay_healthy.yml
=> handle multiple time formats

upstream/roles/deploy_olm_operator_openshift_upstream/defaults/main.yml, upstream/roles/deploy_olm_operator_openshift_upstream/tasks/get_namespace.yml, upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml, upstream/roles/deploy_olm_operator_openshift_upstream/templates/namespace.yml.js2
=> Openshift suggested_namespace

upstream/roles/clean_index_check/tasks/clean_list.yml, upstream/roles/clean_index_check/tasks/get_info.yml, upstream/roles/clean_index_check/tasks/main.yml
=> Fix ptq - file found with no entry

upstream/roles/detect_change/tasks/main.yml, upstream/roles/test_opertator_bundle/tasks/main.yml
=> Rho 909 cosmetic change III

upstream/test/oprt_diff.sh
=> Added oprt_diff

upstream/roles/clean_index_check/tasks/clean_list.yml
=> fix cleaner in case no entry and file exists

upstream/roles/build_operator_index/tasks/main.yml
=> fix replaces check in case of ocp defined

upstream/test/test.sh
=> Disabling fail on no index chage

upstream/roles/detect_change/tasks/main.yml, upstream/test/oprt_cosmetics.sh
=> fix parsing

upstream/roles/detect_change/tasks/main.yml
=> new filter between change lists

upstream/test/oprt.sh
=> Fixed rebase

upstream/roles/operator_push_image/tasks/main.yml
=> Apply expiration label before push during temp-index

upstream/roles/operator_push_image/tasks/main.yml
=> Fix expiration

.github/workflows/otp_upstream_test.yml, upstream/roles/build_operator_index/tasks/main.yml
=> We don't fail when updateGraph is missing

upstream/roles/build_operator_version_bundle/tasks/main.yml
=> Imprved failing when ci.yaml

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml, upstream/roles/deploy_olm_operator_upstream_bundle/tasks/main.yml, upstream/roles/deploy_olm_operator_upstream_bundle/templates/catalogsource_upstream_default.yml.j2
=> External resources

upstream/test/oprt.sh
=> Fix oprt.sh and branch

upstream/test/oprt.sh
=> Improved branch detection

upstream/roles/check_image_availability/tasks/main.yml, upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> csv search

upstream/roles/check_image_availability/tasks/main.yml
=> run on Openshift instead of pull

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> tweaking external image check

upstream/roles/check_image_availability/tasks/main.yml
=> namespace for image check

roles/parse_operator_bundle/defaults/main.yml, upstream/local.yml
=> index v4.8 initialization

upstream/test/test.sh
=> Allow longer wait for Kubernetes deploy

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> retries value

upstream/deploy-olm-operator-openshift-upstream.yml, upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> debug retries

upstream/deploy-olm-operator-openshift-upstream.yml, upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> Pod start final setup

upstream/roles/deploy_olm_operator_openshift_upstream/defaults/main.yml
=> retries default

upstream/test/oprt.sh
=> Fixed parsing correct branch when on master

docs/upstream/README.md, upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/check_index/tasks/main.yml, upstream/roles/export_list_of_packages_from_index/tasks/main.yml, upstream/roles/gather_all_operators_to_dict/tasks/main.yml, upstream/roles/mirror_image/tasks/mirror_single.yml, upstream/roles/remove_operator_bundle/tasks/main.yml, upstream/roles/sync_index_sha/tasks/bundle_sha.yml, upstream/roles/sync_index_sha/tasks/main.yml, upstream/test/test.sh
=> Sha implemented

upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/export_list_of_packages_from_index/defaults/main.yml, upstream/roles/export_list_of_packages_from_index/tasks/main.yml, upstream/roles/sync_index_sha/tasks/bundle_sha.yml, upstream/roles/sync_index_sha/tasks/main.yml
=> Improved sha parsing

upstream/roles/export_list_of_packages_from_index/defaults/main.yml, upstream/roles/sync_index_sha/tasks/main.yml
=> Fix for production

upstream/roles/reset_kind/templates/kind-with-registry.sh.j2
=> Fixed mount

upstream/test/iss.sh
=> iss script implemented

upstream/roles/export_ci_yaml/tasks/main.yml
=> Fix when ci is missing

upstream/roles/detect_format/defaults/main.yml
=> Removing channel.default

upstream/roles/detect_format/tasks/main.yml
=> Fixing check for default label

upstream/roles/parse_operator_bundle/defaults/main.yml, upstream/roles/parse_operator_bundle/tasks/bundle_sanity_checks.yml, upstream/roles/parse_operator_bundle/tasks/main.yml
=> Fix default label

upstream/test/test.sh
=> redHat sha

upstream/local.yml
=> opm bump v1.17.0

upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/build_operator_index_sha/tasks/main.yml
=> Fix bundle images sha when empty

upstream/local.yml
=> Extend cosmetic change

upstream/test/oprt.sh, upstream/test/osr_run.sh
=> Temp index fix - file modification vs delete

upstream/test/oprt.sh
=> allow undefined repo for osr_run

upstream/test/oprt.sh, upstream/test/osr_run.sh
=> prepare variables for temp-index

upstream/test/osr_run.sh
=> extend repo for ors run

upstream/test/osr_run.sh
=> fix commit hash

upstream/roles/build_operator_version_bundle/tasks/main.yml
=> Checking scorecard dir

upstream/test/oprt.sh, upstream/test/osr_run.sh
=> openshift test renamed files

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> debug - subscription, operatorgroup, get pods, get deployments

upstream/test/iss.sh
=> Improved mirroring

upstream/roles/build_operator_index_sha/defaults/main.yml, upstream/roles/build_operator_index_sha/tasks/main.yml, upstream/test/iss.sh, upstream/test/test.sh
=> Added sha add skip

.github/workflows/otp_upstream_test.yml, upstream/roles/build_operator_index/tasks/main.yml, upstream/roles/check_index/tasks/main.yml, upstream/roles/clean_index_check/tasks/clean_list.yml, upstream/roles/clean_index_check/tasks/get_info.yml, upstream/roles/clean_index_check/tasks/main.yml, upstream/roles/detect_operators_in_cluster/tasks/match_index.yml, upstream/roles/detect_operators_in_cluster/tasks/op_ver.yml, upstream/roles/detect_operators_in_cluster/tasks/op_ver_own_logic.yml, upstream/roles/handle_failed_operators/tasks/main.yml, upstream/roles/prepare_catalog_repo_upstream/defaults/main.yml, upstream/roles/prepare_catalog_repo_upstream/tasks/main.yml
Remove Dockerfile support from index_check and detect_operartors_in_cluster
Signed-off-by: Test User <test@example.com>
=> Remove Dockerfile support from index_check and detect_operartors_in_c

upstream/roles/cleanup_operator_resources/tasks/main.yml
=> Failing now when object is not able to delete in 60 sec

upstream/local.yml
=> Fixed typo

upstream/test/iss.sh
=> Moved to mavala

upstream/roles/install_iib/templates/docker-compose.yml.j2
=> Fixing worker

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml, upstream/roles/detect_operators_in_cluster/tasks/op_ver.yml
Signed-off-by: J0zi <jbreza@redhat.com>
=> exit if cluster version is not supported

upstream/local.yml, upstream/roles/validate_operator_bundle/defaults/main.yml, upstream/roles/validate_operator_bundle/tasks/main.yml
=> Testing operator-sdk 1.8

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml, upstream/roles/detect_operators_in_cluster/tasks/op_ver.yml
Reverts operator-framework/operator-test-playbooks#173
=> Revert "exit if cluster version is not supported"

upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
=> upstream settings

upstream/roles/detect_operators_in_cluster/tasks/op_ver.yml
=> Cvp 1793 exit non relevant ocp test ii

upstream/roles/check_image_availability/tasks/main.yml, upstream/roles/deploy_olm_operator_openshift_upstream/tasks/main.yml
Fix after identation and linting
=> Quick fix delete testimagepull

.github/workflows/otp_upstream_test.yml, upstream/roles/build_operator_index_sha/tasks/main.yml, upstream/roles/check_index/defaults/main.yml, upstream/roles/check_index/tasks/main.yml, upstream/roles/export_list_of_packages_from_index/defaults/main.yml, upstream/roles/export_list_of_packages_from_index/tasks/main.yml, upstream/roles/install_docker/tasks/main.yml, upstream/roles/sync_index_sha/tasks/main.yml
=> Testing min_operators_in_index_allowed

upstream/roles/detect_change/tasks/main.yml
=> Fiuxing status

upstream/local.yml, upstream/roles/build_operator_version_bundle/tasks/main.yml
=> Operator sdk validate

upstream/roles/build_operator_version_bundle/tasks/main.yml
=> Removed pause
